trigger: none
pr:
- master

name: 1.0$(Rev:.r)-$(SourceBranchName)

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-18.04

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Dotnet Restore'
      inputs:
        command: restore
        projects: '**/*.sln'
    - template: templates/run-tests-from-projects.yml
